### ISSUE TITLE
Transaction Query does not working well

### ISSUE THREAD

**Issue by hikijs** [hikijs/Blog_Backend#3]

**Comment by sieusaya149** [comment]
* In this project we divide the type of connections is two way (single connection and pool connection).
* With the transaction query in mysql, for successfully commit or rollback, we must ensure that all query in same connection.


Summarize the flow 
```
await TransactionQuery.startTransaction()
        try {
                                                             
            await TransactionQuery.commitTransaction()
            
        } catch (error) {

            await TransactionQuery.rollBackTransaction()      
        }        
```

TransactionQuery.startTransaction() => create a transaction connection 
commitTransaction() or rollBackTransaction()  ==> clear the transaction connection

between them all queries should use the transaction connection was created by startTransaction()


I have test the case pool connection the transaction is good, **but in case single connection we have an mistaken about the name of the varialbe** that lead to when choosing connection to query they alway choose normal connection instead of transaction connection that was created by TransactionQuery.startTransaction() do.


```
async singleConnectionQuery(query, params)
	{
		if(this.isTxConnection)
		{
			return this.sigleTxConnectionQuery(query, params)
		}
		else
		{
			return this.singleConnectionNormalQuery(query, params)
		}
	}
```

the this.isTxConnection should be this.txConnection

**Comment by hikijs** [comment]
#5 is the PR
